// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const createFile = `-- name: CreateFile :one
insert into files (mime, file_size)
values ($1, $2)
returning id, mime, file_size
`

type CreateFileParams struct {
	Mime     string
	FileSize int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile, arg.Mime, arg.FileSize)
	var i File
	err := row.Scan(&i.ID, &i.Mime, &i.FileSize)
	return i, err
}

const getFileById = `-- name: GetFileById :one
select id, mime, file_size from files
where id = $1
`

func (q *Queries) GetFileById(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFileById, id)
	var i File
	err := row.Scan(&i.ID, &i.Mime, &i.FileSize)
	return i, err
}
